channels:
  - conda-forge
dependencies:
  - ccache
  - cffi=1.15.1
  - clang-format
  - click=8.1.3
  - cmake
  - cython=0.29.32
  - doxygen
  - git
  - gperftools
  - keras-applications=1.0.8
  - matplotlib=3.5.3
  - ninja
  - numpy=1.21.6
  - pip
  - pre_commit
  - protobuf=4.21.5
  - python>=3.7,<3.8
  - pyyaml=6.0
  - tensorflow=1.14.0
  - theano=1.0.5
  - yapf=0.32.0
  - pip:
    - asq==1.3
    - breathe==4.34.0
    - cpplint==1.6.1
    - keras==2.2.4
    - livereload==2.6.3
    - nbstripout==0.6.0
    - pcpp==1.20.1
    - pystache==0.6.0
    - sphinx-rtd-theme==1.0.0
    - sphinx-tabs==3.4.0
    - sphinxcontrib-katex==0.9.0
    - sphinxcontrib-napoleon==0.7
